server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=EST
    username: root
    password: passwd
  application:
    name: service-provider

mybatis:
  type-aliases-package: com.xiongcloudprovider.model
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5   # 心跳
    lease-expiration-duration-in-seconds: 15  # 过期
